# Generated by Django 2.1.5 on 2019-02-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrxAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxAddrSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addresses', models.ManyToManyField(related_name='addresses', to='srxapp.SrxAddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxAppSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applications', models.ManyToManyField(related_name='applications', to='srxapp.SrxApplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('application', models.ManyToManyField(related_name='application', to='srxapp.SrxApplication')),
                ('appset', models.ManyToManyField(related_name='appset', to='srxapp.SrxAppSet')),
                ('destaddress', models.ManyToManyField(related_name='destaddress', to='srxapp.SrxAddress')),
                ('destaddrset', models.ManyToManyField(related_name='destaddrset', to='srxapp.SrxAddrSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrxZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='fromzone',
            field=models.ManyToManyField(related_name='fromzone', to='srxapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='srcaddress',
            field=models.ManyToManyField(related_name='srcaddress', to='srxapp.SrxAddress'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='srcaddrset',
            field=models.ManyToManyField(related_name='srcaddrset', to='srxapp.SrxAddrSet'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='tozone',
            field=models.ManyToManyField(related_name='tozone', to='srxapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxapplication',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='srxapp.SrxProtocol'),
        ),
        migrations.AddField(
            model_name='srxaddrset',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srxapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxaddress',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srxapp.SrxZone'),
        ),
    ]
