# Generated by Django 2.1.7 on 2019-03-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srxapp', '0006_auto_20190304_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srxaddress',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='srxaddrset',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='srxaddrset',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='srxapplication',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='srxappset',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='application',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='appset',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='destaddress',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='destaddrset',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='fromzone',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='srcaddress',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='srcaddrset',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='tozone',
        ),
        migrations.DeleteModel(
            name='SrxAddress',
        ),
        migrations.DeleteModel(
            name='SrxAddrSet',
        ),
        migrations.DeleteModel(
            name='SrxApplication',
        ),
        migrations.DeleteModel(
            name='SrxAppSet',
        ),
        migrations.DeleteModel(
            name='SrxPolicy',
        ),
        migrations.DeleteModel(
            name='SrxProtocol',
        ),
        migrations.DeleteModel(
            name='SrxZone',
        ),
    ]
