version: '3.7'

services:
  web_test:
    build: .
    volumes:
      - type: volume
        source: ym_persistent_test
        target: /home/srx-yamlr
      - type: volume
        source: static_data_test
        target: /var/www/srx-yamlr/static/
    networks:
      - nginx_network_test
    expose:
      - "8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind :8000 project.wsgi:application"

  nginx_test:
    image: nginx:1.17.2-alpine
    ports:
      - "8002:8002"
    volumes:
      - ./config/nginx_test:/etc/nginx/conf.d/default.conf
      - type: volume
        source: static_data_test
        target: /var/www/srx-yamlr/static/
    networks:
      - nginx_network_test

  selenium_chrome:
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"
    networks:
      - nginx_network_test

networks:
  nginx_network_test:
    driver: bridge

volumes:
  ym_persistent_test:
  static_data_test: