# Generated by Django 2.1.1 on 2018-10-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrxAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
                ('address_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SrxAddrSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrset_name', models.CharField(max_length=255)),
                ('address', models.ManyToManyField(to='generator.SrxAddress')),
            ],
        ),
        migrations.CreateModel(
            name='SrxApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255)),
                ('application_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SrxAppSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationset_name', models.CharField(max_length=255)),
                ('applications', models.ManyToManyField(to='generator.SrxApplication')),
            ],
        ),
        migrations.CreateModel(
            name='SrxPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('applications', models.ManyToManyField(to='generator.SrxApplication')),
                ('destination_address', models.ManyToManyField(related_name='destination_addresses', to='generator.SrxAddress')),
            ],
        ),
        migrations.CreateModel(
            name='SrxProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SrxZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='from_zone',
            field=models.ManyToManyField(related_name='from_zones', to='generator.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='source_address',
            field=models.ManyToManyField(related_name='source_addresses', to='generator.SrxAddress'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='to_zone',
            field=models.ManyToManyField(related_name='to_zones', to='generator.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxapplication',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='generator.SrxProtocol'),
        ),
        migrations.AddField(
            model_name='srxaddrset',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxaddress',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.SrxZone'),
        ),
    ]
