# Generated by Django 2.1.1 on 2018-11-09 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20181109_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxaddress',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='srxaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
