# Generated by Django 2.1.1 on 2018-11-09 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20181109_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxaddrset',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='srxapplication',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='srxappset',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
