# Generated by Django 2.1.1 on 2018-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20181109_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxpolicy',
            name='appsets',
            field=models.ManyToManyField(related_name='appsets', to='generator.SrxAppSet'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='destination_addrset',
            field=models.ManyToManyField(related_name='destination_addrsets', to='generator.SrxAddrSet'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='source_addrset',
            field=models.ManyToManyField(related_name='source_addrsets', to='generator.SrxAddrSet'),
        ),
    ]
