# Generated by Django 2.1.1 on 2018-11-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20181113_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromzone', models.CharField(max_length=255)),
                ('tozone', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('applications', models.CharField(max_length=255)),
            ],
        ),
    ]
