# Generated by Django 2.1.1 on 2018-11-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_newconfigmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconfigmodel',
            name='configid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newconfigmodel',
            name='applications',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newconfigmodel',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newconfigmodel',
            name='fromzone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newconfigmodel',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newconfigmodel',
            name='tozone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
