# Generated by Django 2.1.1 on 2018-11-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20181120_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewConfigModel',
            new_name='SrxNewConfig',
        ),
    ]
