# Generated by Django 2.1.1 on 2018-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20181120_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srxnewconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='srxnewconfig',
            name='configid',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
