# Generated by Django 2.1.1 on 2018-11-26 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrxAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
                ('address_ip', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='SrxAddrSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrset_name', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('address', models.ManyToManyField(to='cgapp.SrxAddress')),
            ],
        ),
        migrations.CreateModel(
            name='SrxApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('application_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SrxAppSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationset_name', models.CharField(max_length=255)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36)),
                ('applications', models.ManyToManyField(to='cgapp.SrxApplication')),
            ],
        ),
        migrations.CreateModel(
            name='SrxNewConfig',
            fields=[
                ('configid', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('fromzone', models.CharField(default='', max_length=255)),
                ('tozone', models.CharField(default='', max_length=255)),
                ('source', models.CharField(default='', max_length=255)),
                ('destination', models.CharField(default='', max_length=255)),
                ('applications', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SrxPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('applications', models.ManyToManyField(to='cgapp.SrxApplication')),
                ('appsets', models.ManyToManyField(related_name='appsets', to='cgapp.SrxAppSet')),
                ('destination_address', models.ManyToManyField(related_name='destination_addresses', to='cgapp.SrxAddress')),
                ('destination_addrset', models.ManyToManyField(related_name='destination_addrsets', to='cgapp.SrxAddrSet')),
            ],
        ),
        migrations.CreateModel(
            name='SrxProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SrxZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='from_zone',
            field=models.ManyToManyField(related_name='from_zones', to='cgapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='source_address',
            field=models.ManyToManyField(related_name='source_addresses', to='cgapp.SrxAddress'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='source_addrset',
            field=models.ManyToManyField(related_name='source_addrsets', to='cgapp.SrxAddrSet'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='to_zone',
            field=models.ManyToManyField(related_name='to_zones', to='cgapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxapplication',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cgapp.SrxProtocol'),
        ),
        migrations.AddField(
            model_name='srxaddrset',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgapp.SrxZone'),
        ),
        migrations.AddField(
            model_name='srxaddress',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgapp.SrxZone'),
        ),
    ]
