# Generated by Django 2.1.1 on 2018-11-26 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxpolicy',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
