# Generated by Django 2.1.1 on 2018-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0003_auto_20181126_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srxpolicy',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='destination_addrset',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='source_address',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='source_addrset',
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='destaddress',
            field=models.ManyToManyField(related_name='destaddresses', to='cgapp.SrxAddress'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='destaddrset',
            field=models.ManyToManyField(related_name='destaddrsets', to='cgapp.SrxAddrSet'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='srcaddress',
            field=models.ManyToManyField(related_name='srcaddresses', to='cgapp.SrxAddress'),
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='srcaddrset',
            field=models.ManyToManyField(related_name='srcaddrsets', to='cgapp.SrxAddrSet'),
        ),
    ]
