# Generated by Django 2.1.1 on 2018-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0004_auto_20181126_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srxpolicy',
            old_name='appsets',
            new_name='appset',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='applications',
        ),
        migrations.AddField(
            model_name='srxpolicy',
            name='application',
            field=models.ManyToManyField(related_name='applications', to='cgapp.SrxApplication'),
        ),
    ]
