# Generated by Django 2.1.1 on 2018-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0005_auto_20181126_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srxpolicy',
            name='application',
            field=models.ManyToManyField(related_name='application', to='cgapp.SrxApplication'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='appset',
            field=models.ManyToManyField(related_name='appset', to='cgapp.SrxAppSet'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='destaddress',
            field=models.ManyToManyField(related_name='destaddress', to='cgapp.SrxAddress'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='destaddrset',
            field=models.ManyToManyField(related_name='destaddrset', to='cgapp.SrxAddrSet'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='fromzone',
            field=models.ManyToManyField(related_name='fromzone', to='cgapp.SrxZone'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='srcaddress',
            field=models.ManyToManyField(related_name='srcaddress', to='cgapp.SrxAddress'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='srcaddrset',
            field=models.ManyToManyField(related_name='srcaddrset', to='cgapp.SrxAddrSet'),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='tozone',
            field=models.ManyToManyField(related_name='tozone', to='cgapp.SrxZone'),
        ),
    ]
