# Generated by Django 2.1.1 on 2018-12-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0006_auto_20181127_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SrxNewConfig',
        ),
    ]
