# Generated by Django 2.1.1 on 2018-12-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0007_delete_srxnewconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srxaddrset',
            old_name='address',
            new_name='addresses',
        ),
    ]
