# Generated by Django 2.1.1 on 2019-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0009_auto_20181228_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrxDefaultApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
            ],
        ),
    ]
