# Generated by Django 2.1.1 on 2019-01-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0010_srxdefaultapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SrxDefaultApplication',
        ),
        migrations.AlterField(
            model_name='srxapplication',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cgapp.SrxProtocol'),
        ),
    ]
