# Generated by Django 2.1.1 on 2019-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0011_auto_20190107_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srxprotocol',
            name='ptype',
            field=models.CharField(max_length=5),
        ),
    ]
