# Generated by Django 2.1.1 on 2019-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0013_auto_20190108_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srxapplication',
            name='port',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='srxprotocol',
            name='ptype',
            field=models.CharField(max_length=12),
        ),
    ]
