# Generated by Django 2.1.3 on 2019-01-14 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0014_auto_20190108_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxpolicy',
            name='policyid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
