# Generated by Django 2.1.3 on 2019-01-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0015_srxpolicy_policyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srxaddress',
            old_name='uuid',
            new_name='configid',
        ),
        migrations.RenameField(
            model_name='srxaddrset',
            old_name='uuid',
            new_name='configid',
        ),
        migrations.RenameField(
            model_name='srxapplication',
            old_name='uuid',
            new_name='configid',
        ),
        migrations.RenameField(
            model_name='srxappset',
            old_name='uuid',
            new_name='configid',
        ),
        migrations.RenameField(
            model_name='srxpolicy',
            old_name='uuid',
            new_name='configid',
        ),
    ]
