# Generated by Django 2.1.5 on 2019-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0016_auto_20190114_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxaddress',
            name='srxtype',
            field=models.CharField(default='address', editable=False, max_length=12),
        ),
    ]
