# Generated by Django 2.1.5 on 2019-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0017_srxaddress_srxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxaddrset',
            name='srxtype',
            field=models.CharField(default='addrset', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='srxapplication',
            name='srxtype',
            field=models.CharField(default='application', editable=False, max_length=11),
        ),
        migrations.AddField(
            model_name='srxappset',
            name='srxtype',
            field=models.CharField(default='appset', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='srxaddress',
            name='srxtype',
            field=models.CharField(default='address', editable=False, max_length=7),
        ),
    ]
