# Generated by Django 2.1.5 on 2019-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0018_auto_20190204_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srxaddress',
            name='srxtype',
        ),
        migrations.RemoveField(
            model_name='srxaddrset',
            name='srxtype',
        ),
        migrations.RemoveField(
            model_name='srxapplication',
            name='srxtype',
        ),
        migrations.RemoveField(
            model_name='srxappset',
            name='srxtype',
        ),
    ]
