# Generated by Django 2.1.5 on 2019-02-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0020_auto_20190204_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srxaddress',
            name='configid',
        ),
        migrations.RemoveField(
            model_name='srxaddrset',
            name='configid',
        ),
        migrations.RemoveField(
            model_name='srxapplication',
            name='configid',
        ),
        migrations.RemoveField(
            model_name='srxappset',
            name='configid',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='configid',
        ),
        migrations.RemoveField(
            model_name='srxpolicy',
            name='policyid',
        ),
    ]
