# Generated by Django 2.1.7 on 2019-03-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srxapp', '0004_auto_20190301_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='jenk_tkn',
        ),
    ]
