# Generated by Django 2.1.12 on 2019-09-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostVarFilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
