# Generated by Django 2.1.7 on 2019-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srxapp', '0005_remove_usersettings_jenk_tkn'),
    ]

    operations = [
        migrations.AddField(
            model_name='srxpolicy',
            name='policyhash',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='srxpolicy',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
