# Generated by Django 2.1.11 on 2019-08-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srxapp', '0007_auto_20190307_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
